version: '1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=porxy.example
  webserver:
    image: andrisuri/nginxwebserver:v1
    ports:
     - "1441:3000"
    environment:
      - VIRTUAL_HOST=porxy.example
